Fix declaration in switch in print_arm_modifier()
Fixes the following error, seen in CI:

    ../modifiers.c: In function 'print_arm_modifier':
    ../modifiers.c:207:3: error: a label can only be part of a statement and a declaration is not a statement
      207 |   uint64_t cu_size_p0 = value & AFRC_FORMAT_MOD_CU_SIZE_MASK;
          |   ^~~~~~~~